### ISSUE TITLE
The content are not fitted with the card

### ISSUE THREAD

**Issue by SirMajed** [anirudhsharma392/Expansion-Card#15]
Hello, So I have this code
```
return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 15),
      child: ExpansionCard(
        borderRadius: 20,
        background: Image.asset(
          "assets/solar.gif",
          fit: BoxFit.cover,
        ),
        title: Container(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(
                "${note.getTitle()}",
                style: TextStyle(
                  fontSize: 30,
                  color: Colors.white,
                  fontFamily: 'BalooBhai',
                ),
              ),
              Text(
                "${note.getReadableDate()}",
                style: TextStyle(
                  fontSize: 20,
                  color: Colors.white,
                  fontFamily: 'BalooBhai',
                ),
              ),
            ],
          ),
        ),
        children: <Widget>[
          Container(
            alignment: Alignment.centerLeft,
            margin: EdgeInsets.symmetric(horizontal: 7, vertical: 10),
            padding: EdgeInsets.symmetric(horizontal: 12),
            child: Text(
              "${note.getDescription()}",
              // overflow: TextOverflow.ellipsis,
              // maxLines: 4,
              style: TextStyle(
                fontSize: 20,
                fontFamily: 'BalooBhai',
                color: Colors.white,
              ),
            ),
          )
        ],
      ),
    );
```
but the content which is the description are going out of the card. any solutions for that?
Example:
![Screenshot_1](https://user-images.githubusercontent.com/33690366/110251550-10dffe80-7f92-11eb-918f-e0825d911dd6.jpg)

**Comment by SirMajed** [comment]
Any help, please?

**Comment by anirudhsharma392** [comment]
Sorry Ahmed !
But I am running a bit busy this week (due to workload), but I'll definitely try to update the package by this weekend.

**Comment by SirMajed** [comment]
> Sorry Ahmed !
> But I am running a bit busy this week (due to workload), but I'll definitely try to update the package by this weekend.

I really appreciate you, thank you so much! I'm waiting. and I hope you do well in your work

**Comment by EmrePbu** [comment]
children: <Widget>[

        Container(
          alignment: Alignment.centerLeft,
          margin: EdgeInsets.symmetric(horizontal: 7, vertical: 10),
          padding: EdgeInsets.symmetric(horizontal: 12),
          child: FittedBox(
            child: Text(
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque feugiat libero arcu, vitae tristique quam volutpat sed. Curabitur velit enim, feugiat nec dui ac, pretium mattis lacus. Sed scelerisque ",
              // overflow: TextOverflow.ellipsis,
              // maxLines: 4,
              style: TextStyle(
                fontSize: 20,
                color: Colors.white,
              ),
            ),
          ),
        )
      ],
You can solve the problem if you wrap the Text widget with the FittedBox widget.

**Comment by SirMajed** [comment]
> way you can

Thank you but it didn't work, the text are so small now and in one line only.
like this:
![Screenshot_3](https://user-images.githubusercontent.com/33690366/110846757-35ebae80-82bd-11eb-9978-a0680299f880.jpg)

**Comment by EmrePbu** [comment]
> > way you can
> 
> Thank you but it didn't work, the text are so small now and in one line only.
> like this:
> ![Screenshot_3](https://user-images.githubusercontent.com/33690366/110846757-35ebae80-82bd-11eb-9978-a0680299f880.jpg)

I hope this will solve your problem

https://gist.github.com/EmrePbu/fd6c8fb064467a42473ce2313870c2f6

https://user-images.githubusercontent.com/33737009/110906207-af66b980-831c-11eb-84f2-3fa9ca3f1ba6.mp4

**Comment by SirMajed** [comment]
> > > way you can
> > 
> > 
> > Thank you but it didn't work, the text are so small now and in one line only.
> > like this:
> > ![Screenshot_3](https://user-images.githubusercontent.com/33690366/110846757-35ebae80-82bd-11eb-9978-a0680299f880.jpg)
> 
> I hope this will solve your problem
> 
> https://gist.github.com/EmrePbu/fd6c8fb064467a42473ce2313870c2f6
> 
>  Screen_Recording_20210312-101914.mp4

Thank you so so much that really worked and helped. I also wrapped the `SingleChildScrollView` with `Scrollbar` and it looks more awesome now!! Thank you
